version: "3.9"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: intranet
      POSTGRES_PASSWORD: intranet123
      POSTGRES_DB: intranet
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://intranet:intranet123@db:5432/intranet
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: change-me-please

volumes:
  db:
